[project]
name = "animations"
version = "0.1.0"
description = "Animated explanations for Tangled Program Graphs, powered by Manim."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.19.0",
    "pydub>=0.25.1",
]
